export const cardTransferDryRun = {
  version: "b323",
  sourceProject: "plate-physical-lab",
  targetProject: "tuev-card",
  sourceBase: ".",
  targetBase: "src/plate/lab-renderer",
  mode: "manifest-only",
  activeCardRendererUnchanged: true,
  productionFiles: [
    "src/plate/chain-solver.js",
    "src/plate/change-plate-slot-plan.js",
    "src/plate/change-plate-supplement-renderer.js",
    "src/plate/change-plate.js",
    "src/plate/eu-country-mark.js",
    "src/plate/eu-star-wreath.js",
    "src/plate/euro-field.js",
    "src/plate/mm-model.js",
    "src/plate/plate-body.js",
    "src/plate/plate-format-strategy.js",
    "src/plate/plate-layout-model.js",
    "src/plate/plate-layout-result-utils.js",
    "src/plate/plate-number-utils.js",
    "src/plate/plate-public-api.js",
    "src/plate/plate-render-context.js",
    "src/plate/plate-render-shell.js",
    "src/plate/plate-rules.js",
    "src/plate/plate-season-options.js",
    "src/plate/plate-sequence-width-utils.js",
    "src/plate/plate-spacing-surface-utils.js",
    "src/plate/plate-svg-renderer.js",
    "src/plate/plate-variant-rules.js",
    "src/plate/plate-visual-style.js",
    "src/plate/plate-width-strategy.js",
    "src/plate/reduced-row-chain-solver.js",
    "src/plate/row-layout-adapter.js",
    "src/plate/row-sequence-builder.js",
    "src/plate/seal-components.js",
    "src/plate/seal-geometry-plan.js",
    "src/plate/seal-marker-plan.js",
    "src/plate/seal-slot-marker.js",
    "src/plate/season-field.js",
    "src/plate/spacing-solver.js",
    "src/plate/svg-escape-utils.js",
    "src/plate/text-utils.js"
  ],
  targetMappings: [
    { source: "src/plate/chain-solver.js", target: "src/plate/lab-renderer/chain-solver.js" },
    { source: "src/plate/change-plate-slot-plan.js", target: "src/plate/lab-renderer/change-plate-slot-plan.js" },
    { source: "src/plate/change-plate-supplement-renderer.js", target: "src/plate/lab-renderer/change-plate-supplement-renderer.js" },
    { source: "src/plate/change-plate.js", target: "src/plate/lab-renderer/change-plate.js" },
    { source: "src/plate/eu-country-mark.js", target: "src/plate/lab-renderer/eu-country-mark.js" },
    { source: "src/plate/eu-star-wreath.js", target: "src/plate/lab-renderer/eu-star-wreath.js" },
    { source: "src/plate/euro-field.js", target: "src/plate/lab-renderer/euro-field.js" },
    { source: "src/plate/mm-model.js", target: "src/plate/lab-renderer/mm-model.js" },
    { source: "src/plate/plate-body.js", target: "src/plate/lab-renderer/plate-body.js" },
    { source: "src/plate/plate-format-strategy.js", target: "src/plate/lab-renderer/plate-format-strategy.js" },
    { source: "src/plate/plate-layout-model.js", target: "src/plate/lab-renderer/plate-layout-model.js" },
    { source: "src/plate/plate-layout-result-utils.js", target: "src/plate/lab-renderer/plate-layout-result-utils.js" },
    { source: "src/plate/plate-number-utils.js", target: "src/plate/lab-renderer/plate-number-utils.js" },
    { source: "src/plate/plate-public-api.js", target: "src/plate/lab-renderer/plate-public-api.js" },
    { source: "src/plate/plate-render-context.js", target: "src/plate/lab-renderer/plate-render-context.js" },
    { source: "src/plate/plate-render-shell.js", target: "src/plate/lab-renderer/plate-render-shell.js" },
    { source: "src/plate/plate-rules.js", target: "src/plate/lab-renderer/plate-rules.js" },
    { source: "src/plate/plate-season-options.js", target: "src/plate/lab-renderer/plate-season-options.js" },
    { source: "src/plate/plate-sequence-width-utils.js", target: "src/plate/lab-renderer/plate-sequence-width-utils.js" },
    { source: "src/plate/plate-spacing-surface-utils.js", target: "src/plate/lab-renderer/plate-spacing-surface-utils.js" },
    { source: "src/plate/plate-svg-renderer.js", target: "src/plate/lab-renderer/plate-svg-renderer.js" },
    { source: "src/plate/plate-variant-rules.js", target: "src/plate/lab-renderer/plate-variant-rules.js" },
    { source: "src/plate/plate-visual-style.js", target: "src/plate/lab-renderer/plate-visual-style.js" },
    { source: "src/plate/plate-width-strategy.js", target: "src/plate/lab-renderer/plate-width-strategy.js" },
    { source: "src/plate/reduced-row-chain-solver.js", target: "src/plate/lab-renderer/reduced-row-chain-solver.js" },
    { source: "src/plate/row-layout-adapter.js", target: "src/plate/lab-renderer/row-layout-adapter.js" },
    { source: "src/plate/row-sequence-builder.js", target: "src/plate/lab-renderer/row-sequence-builder.js" },
    { source: "src/plate/seal-components.js", target: "src/plate/lab-renderer/seal-components.js" },
    { source: "src/plate/seal-geometry-plan.js", target: "src/plate/lab-renderer/seal-geometry-plan.js" },
    { source: "src/plate/seal-marker-plan.js", target: "src/plate/lab-renderer/seal-marker-plan.js" },
    { source: "src/plate/seal-slot-marker.js", target: "src/plate/lab-renderer/seal-slot-marker.js" },
    { source: "src/plate/season-field.js", target: "src/plate/lab-renderer/season-field.js" },
    { source: "src/plate/spacing-solver.js", target: "src/plate/lab-renderer/spacing-solver.js" },
    { source: "src/plate/svg-escape-utils.js", target: "src/plate/lab-renderer/svg-escape-utils.js" },
    { source: "src/plate/text-utils.js", target: "src/plate/lab-renderer/text-utils.js" }
  ],
  labOnlyFiles: [
    "src/plate/debug-dimensions.js",
    "src/plate/plate-lab-debug-renderers.js",
    "src/plate/regression-cases.js",
    "app.js",
    "viewer-calibration.js",
    "font-calibration.js",
    "scripts/run-regression.mjs",
    "reference/"
  ],
  cardFilesToKeep: [
    "src/plate/font.js"
  ],
  cardFilesToReplaceLater: [
    "src/plate/renderer.js",
    "src/plate/mm-model.js"
  ]
};
